mysql-operator:
  orchestrator:
    config:
      # `reset slave all` and `set read_only=0` on promoted master
      ApplyMySQLPromotionAfterMasterFailover: true
    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/auth-type: basic
        nginx.ingress.kubernetes.io/auth-secret: basic-auth
      hosts:
      - host: nip.io
        paths:
          - /

database:
  create: true
  size: 1Gi
  replicas: 3
