ingress:
  enabled: true
  annotations:
    cert-manager.io/issuer: letsencrypt
  rules:
    - host: keycloak.plgrnd.be
      paths:
        - /
  tls:
    - hosts:
        - keycloak.plgrnd.be
      secretName: keycloak-tls

extraEnv: |
  - name: KEYCLOAK_USER
    value: admin
  - name: KEYCLOAK_PASSWORD
    value: admin
  - name: JAVA_OPTS
    value: >-
      -Dkeycloak.frontendUrl=https://keycloak.plgrnd.be/auth