image:
  tag: ""

ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  paths: []
  host: nip.io
  tls: []
    - secretName: store.geekosoup.com-tls
      hosts:
        - store.geekosoup.com

loadGenerator:
  enabled: true

monitoring:
  enabled: true
